apiVersion: apps/v1
kind: Deployment
metadata:
  name: brtaks01
spec:
  selector:
    matchLabels:
      app: brtaks01-pod
  template:
    metadata:
      labels:
        app: brtaks01-pod
    spec:
      containers:
      - name: brtaks01-container
        image: cloudnativeacr01.azurecr.io/brtaks01:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
